version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-repo:latest
    ports:
      - "3000:3000"
    links:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
